# Generated by Django 2.0.3 on 2018-03-20 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('poke_nr', models.IntegerField(primary_key=True, serialize=False)),
                ('poke_name_ger', models.CharField(max_length=30)),
                ('poke_name_eng', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('poke_nr',),
            },
        ),
        migrations.CreateModel(
            name='PokePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_report_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('poke_lvl', models.IntegerField(default=0)),
                ('poke_iv', models.FloatField(default=0.0)),
                ('poke_lat', models.FloatField()),
                ('poke_lon', models.FloatField()),
                ('poke_despawn_time', models.DateTimeField()),
                ('poke_nr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Pokemon')),
            ],
        ),
    ]
