# Generated by Django 2.1.5 on 2019-04-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='SightingsTemp',
        ),
    ]
