# Generated by Django 2.1.4 on 2018-12-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180417_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonspawn',
            old_name='poke_nr',
            new_name='pokemon_object',
        ),
        migrations.AddField(
            model_name='pokemonspawn',
            name='encounter_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
