# Generated by Django 2.1.4 on 2018-12-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_spawnpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='spawnpoint',
            name='spawn_point_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='spawnpoint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
