# Generated by Django 2.1.4 on 2018-12-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20181204_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('quest_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('quest_type', models.BigIntegerField()),
                ('pokestop_id', models.CharField(max_length=128)),
                ('quest_timestamp', models.IntegerField()),
                ('quest_conditions', models.TextField()),
                ('quest_rewards', models.TextField()),
                ('quest_template', models.CharField(max_length=128)),
                ('quest_pokemon_id', models.SmallIntegerField(default=None, null=True)),
                ('quest_reward_type', models.SmallIntegerField(default=None, null=True)),
                ('quest_item_id', models.SmallIntegerField(default=None, null=True)),
                ('quest_item_amount', models.SmallIntegerField(default=None, null=True)),
                ('target', models.SmallIntegerField(default=None, null=True)),
                ('cell_id', models.BigIntegerField()),
            ],
        ),
    ]
