# Generated by Django 2.1.4 on 2018-12-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='quest_item_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
