# Generated by Django 2.1.4 on 2018-12-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20181208_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='quest_reward_type',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
