# Generated by Django 2.1.4 on 2018-12-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20181209_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='quest_timestamp',
            field=models.BigIntegerField(),
        ),
    ]
