# Generated by Django 2.1.4 on 2018-12-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20181211_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonspawn',
            name='moves',
            field=models.ManyToManyField(blank=True, default=None, to='myapp.PokemonMove'),
        ),
    ]
