# Generated by Django 2.1.3 on 2018-12-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20181214_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='active_fort_modifier',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='image_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='last_modified',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='poi_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
