# Generated by Django 2.1.3 on 2018-12-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20181215_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymPointOfInterest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('myapp.pointofinterest',),
        ),
        migrations.AlterField(
            model_name='raid',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.GymPointOfInterest'),
        ),
    ]
