# Generated by Django 2.2.6 on 2019-10-01 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDiscordServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('P', 'pokestop'), ('G', 'gym'), ('S', 'spawn')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pokedex',
            fields=[
                ('pokemon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('name_ger', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('name_fr', models.CharField(blank=True, default=None, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=128)),
                ('message_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.MessageType')),
            ],
        ),
    ]
