# Generated by Django 2.0.2 on 2018-03-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokeposition',
            name='poke_iv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokeposition',
            name='poke_lvl',
            field=models.IntegerField(default=0),
        ),
    ]
